import type { Metadata } from 'next';
import { PublicHeader } from '@/components/public/public-header';
import { PublicFooter } from '@/components/public/public-footer';

export const metadata: Metadata = { title: 'Privacy Policy' };

export default function PrivacyPage() {
  return <div className="min-h-svh bg-white"><PublicHeader /><main className="prose-policy"><p className="policy-eyebrow">Legal</p><h1>Privacy Policy</h1><p className="policy-lead">Last updated: 28 August 2026</p><section><h2>What we collect</h2><p>We collect account details, creator or brand profile information, structured campaign and offer terms, declared social metrics, uploaded assets, subscription events, and product usage needed to operate Collab Deal OS.</p></section><section><h2>How we use data</h2><p>We use this information to authenticate accounts, match creators and campaigns, calculate deterministic deal ranges, generate requested AI explanations, preserve offer revisions, prevent abuse, and provide account support.</p></section><section><h2>Declared and verified metrics</h2><p>V1 social metrics are entered by creators and labeled Creator Declared. We do not infer follower counts from profile URLs or scrape social platforms. Future official API checks will be labeled API Verified.</p></section><section><h2>Security and service providers</h2><p>Private provider keys are kept server-side. Authorized infrastructure providers may process limited data for authentication, hosting, AI explanations, payments, transactional email, and analytics under their applicable terms.</p></section><section><h2>Your choices</h2><p>You may update your profile, notification preferences, and account information. Account deletion and data-access requests will be handled through account support when production support channels are configured.</p></section><section><h2>Contact</h2><p>This policy is an initial product policy and must be reviewed with production company details and a legal contact before public launch.</p></section></main><PublicFooter /></div>;
}
