import type { Metadata } from 'next';
import { PublicHeader } from '@/components/public/public-header';
import { PublicFooter } from '@/components/public/public-footer';

export const metadata: Metadata = { title: 'Privacy Policy' };

export default function PrivacyPage() {
  return <div className="min-h-svh bg-white"><PublicHeader /><main className="prose-policy"><p className="policy-eyebrow">Legal</p><h1>Privacy Policy</h1><p className="policy-lead">Last updated: 17 September 2026</p><section><h2>What we collect</h2><p>We collect account details, creator or brand profile information, collaboration deals, offer terms, declared social metrics, uploaded assets, brand–creator messages, security and recovery events, and product usage needed to operate Collab Deal OS.</p></section><section><h2>How we use data</h2><p>We use this information to authenticate accounts, operate creator discovery and campaign workflows, support brand–creator conversations and offers, protect account actions, prevent abuse, and provide account support.</p></section><section><h2>Declared and verified metrics</h2><p>Creator social metrics are entered by creators and labeled Creator Declared unless a future official platform integration verifies them. We do not infer follower counts from profile URLs or scrape social platforms.</p></section><section><h2>Security and service providers</h2><p>Private provider keys are kept server-side. Authorized infrastructure providers may process limited data for authentication, hosting, transactional email, analytics, and future payment services when those services are enabled, under their applicable terms.</p></section><section><h2>Your choices</h2><p>You may update your profile, preferences, and account information. Account deletion is available from Settings and is protected by the account payment password. Payment-password recovery uses the signed-in account email and a verification-code flow.</p></section><section><h2>Prototype status</h2><p>Some wallet and payment features are currently prototype simulations and do not represent live money movement. Production payment processing will require a compliant payment provider before launch.</p></section><section><h2>Contact</h2><p>This is an initial product privacy policy and should be reviewed with final company details, support contact information, and legal counsel before a public production launch.</p></section></main><PublicFooter /></div>;
}
