import Link from 'next/link';
import { ArrowRight, Bot, CircleAlert, Clock3 } from 'lucide-react';
import { formatInr } from '@/lib/utils';
import type { AccountType } from '@/types/domain';
import type { DealAnalysisRecord } from '@/types/analysis';

export function AnalysisHistory({ role, analyses }: { role: AccountType; analyses: DealAnalysisRecord[] }) {
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-violet-50 text-violet-700"><Clock3 className="size-5" /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-violet-700">History</p><h2 className="mt-1 text-lg font-bold text-slate-950">Recent evaluations</h2></div></div>{analyses.length ? <div className="mt-5 grid gap-3">{analyses.map((analysis) => <Link className="group grid gap-3 rounded-xl border border-slate-200 p-4 transition hover:border-violet-200 hover:bg-violet-50/30 sm:grid-cols-[1fr_auto_auto] sm:items-center" href={`/${role}/analysis/${analysis.id}`} key={analysis.id}><div className="flex items-start gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-600">{analysis.status === 'FAILED' ? <CircleAlert className="size-4" /> : <Bot className="size-4" />}</span><div><strong className="block text-sm text-slate-900">{analysis.offerId ? 'Linked offer analysis' : 'Manual deal analysis'}</strong><span className="mt-1 block text-xs text-slate-400">{new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(analysis.createdAt))} · {analysis.status}</span></div></div><span className="text-xs font-semibold text-slate-600">{analysis.fairLow != null && analysis.fairHigh != null ? `${formatInr(analysis.fairLow)}–${formatInr(analysis.fairHigh)}` : 'No verdict'}</span><ArrowRight className="size-4 text-slate-400 transition group-hover:translate-x-1 group-hover:text-violet-700" /></Link>)}</div> : <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Your completed and failed evaluations will appear here with their immutable snapshots.</p>}</section>;
}
