import Link from 'next/link';
import { ArrowLeft, Bot, CalendarClock, IndianRupee, ListChecks, Package, ShieldCheck, Sparkles } from 'lucide-react';
import { OfferActionPanel } from './offer-action-panel';
import { OfferStatus } from './offer-status';
import { formatInr } from '@/lib/utils';
import type { AccountType } from '@/types/domain';
import type { OfferEvent, OfferFeedItem, OfferRevision } from '@/types/offers';
import type { OfferInput } from '@/lib/validation/offer';

export function OfferDetails({ role, accountId, offer, revisions, events }: { role: AccountType; accountId: string; offer: OfferFeedItem; revisions: OfferRevision[]; events: OfferEvent[] }) {
  const otherName = role === 'creator' ? offer.brandName : offer.creatorName;
  const otherImage = role === 'creator' ? offer.brandLogoUrl : offer.creatorAvatarUrl;
  const initialValues: OfferInput = {
    cashPayment: offer.cashPayment, productName: offer.productName ?? '', productValue: offer.productValue,
    dealType: offer.dealType, deliverables: offer.deliverables.map((item) => ({ ...item, notes: item.notes ?? '' })),
    usageRights: offer.usageRights ?? '', usageDurationDays: offer.usageDurationDays ?? undefined,
    paidAdRights: offer.paidAdRights, exclusivity: offer.exclusivity,
    exclusivityDurationDays: offer.exclusivityDurationDays ?? undefined,
    deadline: offer.deadline ? new Date(offer.deadline).toISOString().slice(0, 16) : '',
    territory: offer.territory ?? '', notes: offer.notes ?? '',
  };

  return <>
    <Link className="inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-slate-500 transition hover:text-slate-950" href={`/${role}/offers`}><ArrowLeft className="size-4" />Offers</Link>
    <div className="mt-3 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="flex items-start gap-4"><span className="flex size-14 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-100 to-blue-100 bg-cover bg-center text-lg font-bold text-violet-700" style={otherImage ? { backgroundImage: `url(${JSON.stringify(otherImage).slice(1, -1)})` } : undefined}>{!otherImage ? otherName.slice(0, 1).toUpperCase() : null}</span><div><div className="flex flex-wrap items-center gap-2"><OfferStatus status={offer.status} /><span className="text-[10px] font-bold uppercase tracking-[0.08em] text-slate-400">Version {offer.version}</span></div><h1 className="mt-2 text-2xl font-bold tracking-[-0.04em] text-slate-950 sm:text-3xl">Offer with {otherName}</h1><p className="mt-2 text-sm text-slate-500">{offer.campaignTitle ?? 'Standalone collaboration offer'} · {direction(role, offer)}</p></div></div><Link className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-blue-600 px-4 text-sm font-semibold text-white" href={`/${role}/ai-advisor?offer=${offer.offerId}`}><Sparkles className="size-4" />Analyze with AI</Link></div>

    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary icon={IndianRupee} label="Cash payment" value={formatInr(offer.cashPayment)} detail="Current version" /><Summary icon={Package} label="Product value" value={offer.productValue ? formatInr(offer.productValue) : 'None'} detail={offer.productName ?? 'No product included'} /><Summary icon={IndianRupee} label="Combined value" value={formatInr(offer.cashPayment + offer.productValue)} detail={offer.dealType.replaceAll('_', ' ')} /><Summary icon={Bot} label="Latest AI score" value={offer.latestAnalysisScore != null ? `${offer.latestAnalysisScore}/100` : 'Not analyzed'} detail="Personal analysis history" /></section>

    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.25fr)_360px]">
      <div className="grid content-start gap-6">
        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><ListChecks className="size-5" /></span><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-blue-700">Current offer</p><h2 className="mt-1 text-lg font-bold text-slate-950">Deliverables</h2></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{offer.deliverables.map((item, index) => <div className="flex items-start justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50 p-4" key={`${item.type}-${index}`}><div><strong className="text-sm text-slate-900">{item.type}</strong>{item.notes ? <p className="mt-1 text-xs leading-5 text-slate-500">{item.notes}</p> : null}</div><span className="rounded-lg bg-white px-2.5 py-1 text-xs font-bold text-slate-700">×{item.quantity}</span></div>)}</div></section>

        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-emerald-600" /><h2 className="text-lg font-bold text-slate-950">Rights, timing, and conditions</h2></div><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Detail label="Usage rights" value={offer.usageRights ?? 'Not specified'} /><Detail label="Usage duration" value={offer.usageDurationDays != null ? `${offer.usageDurationDays} days` : 'Not specified'} /><Detail label="Paid advertising" value={offer.paidAdRights ? 'Included' : 'Not included'} /><Detail label="Exclusivity" value={offer.exclusivity ? `${offer.exclusivityDurationDays ?? '—'} days` : 'Not included'} /><Detail label="Territory" value={offer.territory ?? 'Not specified'} /><Detail label="Decision deadline" value={offer.deadline ? formatDate(offer.deadline) : 'Not specified'} /></dl>{offer.notes ? <div className="mt-5 border-t border-slate-100 pt-4"><p className="text-[10px] font-bold uppercase tracking-[0.08em] text-slate-400">Structured context</p><p className="mt-2 text-sm leading-6 text-slate-600">{offer.notes}</p></div> : null}</section>

        <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-violet-700">Audit trail</p><h2 className="mt-1 text-lg font-bold text-slate-950">Offer revisions</h2><p className="mt-1 text-xs text-slate-500">Original Offer → revisions → current offer. Records are immutable.</p></div>{revisions.length ? <div className="mt-5 grid gap-4">{revisions.map((revision) => <article className="rounded-2xl border border-slate-200 p-4" key={revision.id}><div className="flex items-center justify-between gap-3"><div><strong className="text-sm text-slate-950">Revision {revision.toVersion - 1}</strong><span className="ml-2 text-xs text-slate-400">v{revision.fromVersion} → v{revision.toVersion}</span></div><span className="text-[10px] font-semibold text-slate-400">{revision.changedBy === accountId ? 'Changed by you' : `Changed by ${otherName}`} · {formatDate(revision.createdAt)}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{revision.changedFields.map((field) => <div className="rounded-xl bg-slate-50 p-3" key={field}><span className="text-[10px] font-bold uppercase tracking-[0.06em] text-slate-400">{fieldLabel(field)}</span><div className="mt-2 grid grid-cols-[1fr_auto_1fr] items-center gap-2 text-xs"><span className="truncate text-slate-400">{formatRevisionValue(revision.oldValues[field], field)}</span><span className="text-slate-300">→</span><strong className="truncate text-slate-800">{formatRevisionValue(revision.newValues[field], field)}</strong></div></div>)}</div></article>)}</div> : <div className="mt-5 rounded-xl bg-slate-50 p-4 text-sm text-slate-500">This is the original offer. No term revisions have been submitted.</div>}</section>
      </div>
      <aside className="grid content-start gap-6 xl:sticky xl:top-24"><OfferActionPanel offerId={offer.offerId} version={offer.version} role={role} status={offer.status} pendingWith={offer.pendingWith} initialValues={initialValues} /><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[0.12em] text-blue-700">Decision history</p><h2 className="mt-1 text-sm font-bold text-slate-950">Shared status events</h2><div className="mt-4 grid gap-3">{events.map((event) => <div className="grid grid-cols-[8px_1fr] gap-3" key={event.id}><span className="mt-1.5 size-2 rounded-full bg-violet-500" /><div><strong className="block text-xs text-slate-800">{fieldLabel(event.eventType)}</strong><span className="mt-0.5 block text-[10px] text-slate-400">v{event.version} · {event.actorUserId ? event.actorUserId === accountId ? 'You' : otherName : 'System'} · {formatDate(event.createdAt)}</span></div></div>)}</div></section>{offer.campaignId ? <Link className="flex min-h-11 items-center justify-between rounded-xl border border-slate-200 bg-white px-4 text-xs font-semibold text-slate-700" href={role === 'brand' ? `/brand/campaigns/${offer.campaignId}` : `/creator/opportunities/${offer.campaignId}`}>View linked campaign<CalendarClock className="size-4 text-slate-400" /></Link> : null}</aside>
    </div>
  </>;
}

function Summary({ icon: Icon, label, value, detail }: { icon: typeof IndianRupee; label: string; value: string; detail: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="text-xs font-semibold text-slate-500">{label}</span><Icon className="size-4 text-violet-600" /></div><strong className="mt-3 block truncate text-xl font-bold tracking-[-0.03em] text-slate-950">{value}</strong><span className="mt-1 block truncate text-[10px] text-slate-400">{detail}</span></div>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-[10px] font-bold uppercase tracking-[0.08em] text-slate-400">{label}</dt><dd className="mt-1 text-sm font-semibold leading-6 text-slate-700">{value}</dd></div>; }
function direction(role: AccountType, offer: OfferFeedItem) { if (!offer.pendingWith) return 'Decision recorded'; return offer.pendingWith === role ? 'Your action required' : `Awaiting ${offer.pendingWith}`; }
function formatDate(value: string) { return new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); }
function fieldLabel(value: string) { return value.replaceAll('_', ' ').replace(/^./, (letter) => letter.toUpperCase()); }
function formatRevisionValue(value: unknown, field: string) { if (value == null || value === '') return 'None'; if (field.includes('payment') || field.includes('value')) return formatInr(Number(value)); if (typeof value === 'boolean') return value ? 'Included' : 'Not included'; if (Array.isArray(value)) return `${value.length} item${value.length === 1 ? '' : 's'}`; if (field === 'deadline') return formatDate(String(value)); return String(value); }
